// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AlwaysOnTopButton: typeof import('./../components/AlwaysOnTopButton.vue')['default']
    AnimeNumber: typeof import('./../components/AnimeNumber.vue')['default']
    AppLockButton: typeof import('./../components/AppLockButton.vue')['default']
    ConfirmButton: typeof import('./../components/ConfirmButton.vue')['default']
    DarkButton: typeof import('./../components/DarkButton.vue')['default']
    EditButton: typeof import('./../components/EditButton.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EpMoon: typeof import('~icons/ep/moon')['default']
    EpSunny: typeof import('~icons/ep/sunny')['default']
    FlatUiYinyang: typeof import('~icons/flat-ui/yinyang')['default']
    FocusLockButton: typeof import('./../components/FocusLockButton.vue')['default']
    LocaleButton: typeof import('./../components/LocaleButton.vue')['default']
    MdiLockOpenVariantOutline: typeof import('~icons/mdi/lock-open-variant-outline')['default']
    MdiLockOutline: typeof import('~icons/mdi/lock-outline')['default']
    MdiSquareEditOutline: typeof import('~icons/mdi/square-edit-outline')['default']
    MyHeader: typeof import('./../layout/components/MyHeader.vue')['default']
    MyMain: typeof import('./../layout/components/MyMain.vue')['default']
    MyMenu: typeof import('./../layout/components/MyMenu.vue')['default']
    MyMenuItem: typeof import('./../layout/components/MyMenuItem.vue')['default']
    RiTranslate: typeof import('~icons/ri/translate')['default']
  }
}

export { }
