parser: "@typescript-eslint/parser"
parserOptions:
  parser: "@typescript-eslint/parser"
  ecmaVersion: 2021
  sourceType: "module"
  ecmaFeatures:
    jsx: true
extends:
  - "eslint:recommended"
  - "prettier"
  - "plugin:prettier/recommended"
  - "plugin:node/recommended"
rules:
  "node/no-missing-import": "off"
  "node/no-unpublished-import": "off"
  "node/no-unsupported-features/es-syntax": "off"
  "prettier/prettier": "error"
  semi: error

