name: 提交编译测试
on:
  push:
    tags-ignore:
      - "v*.*.*"
  pull_request:
    branches:
      - "dev"

jobs:
  build:
    name: 编译 html
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 安装依赖 & 编译 html
        run: |
          echo 开始
          cd tool-web
          echo 安装依赖
          yarn
          echo 编译 html
          yarn build
          echo 完成

      - name: 安装依赖 & 编译 electron
        run: |
          echo 开始
          echo 创建 dist 目录
          mkdir tool-electron/dist
          echo 复制 html 至 dist 目录
          cp -rf tool-web/dist/* tool-electron/dist/
          cd tool-electron
          echo 安装依赖
          yarn
          echo 编译 electron
          yarn build:dir
          echo 完成