name: 编译代码 & 更新 github pages 分支
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    name: 编译代码 & 更新 github pages 分支
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 安装依赖 & 编译web代码
        run: |
          cd tool-web
          npm install --global yarn
          yarn set version berry
          yarn
          yarn build

      - name: 上传至 github pages 分支
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: tool-web/dist